### ISSUE TITLE
(nodejs.install) 19.0.0 verfication failed

### ISSUE THREAD

**Issue by majkinetor** [chocolatey-community/chocolatey-packages#2027]
### Chocolatey Version

1.1.0

### Package Version

19.0.0

### Current Behaviour

- [nodejs log](https://gist.github.com/choco-bot/54a6bf6c5773c56316a18fd05f7449aa)
- [nodejs.install log](https://gist.github.com/choco-bot/7268855f9d1bc8d3cdb57a572a069d08)

**Comment by majkinetor** [comment]
@pauby , still not present, wasn't repeated

**Comment by pauby** [comment]
Package wasn't pushed after the merge. I pushed it just now.

**Comment by pauby** [comment]
This is now approved.

**Comment by majkinetor** [comment]
Its not fixed.

**Comment by majkinetor** [comment]
Nor it works...

![image](https://user-images.githubusercontent.com/85767/199972996-fe216a60-cca9-4d51-b453-89afea5a1fa7.png)

**Comment by majkinetor** [comment]
Still doesn't work right. There is no more nodejs on the PATH like on previous versions.

**Comment by majkinetor** [comment]
Actually, there is no node at all:

![image](https://user-images.githubusercontent.com/85767/200039511-cbee7bc4-e5ba-4dc7-a495-96f19a184b1c.png)

**Comment by pauby** [comment]
This for failed verification package has now passed verification so we can close it. If it's still broken, a new issue should be opened for that.

Not sure if this is an installer problem or another parameter needs passed to the MSI or _something else_.

**Comment by pauby** [comment]
Actually, verification _hasn't_ passed yet. Still in moderation. Let see how it gets on.

**Comment by majkinetor** [comment]
> This for failed verification package has now passed verification so we can close it

That is irrelevant. Antyhing can pass validation if one wants to do so.

**Comment by majkinetor** [comment]
What needs to be done is adequate test, not just code changes and hope it works.

**Comment by pauby** [comment]
I'm going to close this issue as the package has now passed Verifier. That's what the issue was about. And that's what was tested for - the package installed and uninstalled and then passed Package Verifier.

If the path is not being added, please raise another issue for that as it's an entirely different problem from what this issue was raised for.

**Comment by majkinetor** [comment]
Lets call it a day then. Good job :)

**Comment by pauby** [comment]
After installing nodejs.install and rebooting the machine, it appears on the path. Did you try that?

![image](https://user-images.githubusercontent.com/12760779/200044436-ed929166-be6a-4c68-9c3b-103529faf324.png)

**Comment by majkinetor** [comment]
Yes I did. 
I tried it now in a Sandbox and it works there (no restart of OS needed, just shell)

It turns out it didn't install node on my OS but it did in the sandbox:

![image](https://user-images.githubusercontent.com/85767/200048753-d7108bbf-72fe-4b0a-8274-c54d3c2d708b.png)

I don't have AV so this is highly strange. When forceed nodejs.install instead of nodejs it worked.

Thx for your help.
